application: 2134125
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.png

- url: /(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))
   
- url: /.*
  script: scripts/main.py